apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-server
  namespace: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-server
  template:
    metadata:
      labels:
        app: actual-server
    spec:
      containers:
        - name: actual-server
          image: actualbudget/actual-server:latest
          ports:
            - containerPort: 5006
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tls
              mountPath: /etc/tls
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-pvc
        - name: tls
          secret:
            secretName: tracking-secret-tls
