apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: tracking
spec:
  selector:
    app: vaultwarden-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
