apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: tracking
spec:
  type: NodePort
  selector:
    app: vaultwarden-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30581
