apiVersion: v1
kind: Secret
metadata:
    name: tracking-auth-token
    namespace: tracking
type: Opaque
data:
    auth-token: ENC[AES256_GCM,data:BOygfBBgfMhsUcOxlK4U8yUYaUg=,iv:D3nBocE4I6gp7RWjzo9mCLbc/Re+27gZYOQroW2X9i4=,tag:vEOWMc3vPqpLLW0bW0W7gw==,type:str]
sops:
    age:
        - recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSm5XMm9kWDhBQVZkTnBZ
            Tm1QSWNWc3hQTjV0a2JybW1yS2pkZCt4bVJNCndDM1V2ZEhOeHdjTWVrZFBTUXFN
            U21YRzR0MktDUEtZbStLaVNlMitUdVkKLS0tIFprbXYzY1dYYXNST3dHVGJML29R
            bWs5cUJxMEgwcTZKYStGdFJvNDRUcjQKe86j3auwXiwRIYttfWwdc5vBvBzx2Bt4
            IZwupnmyVd3yTYe3WTLwfI6ZEcwef7j2C9HgK8kBZb1nPIqIxmqzYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T17:52:20Z"
    mac: ENC[AES256_GCM,data:m+meyoLfxrvMLCkaucKQzTtHTXlP3gMfuvRPKwcEMd89u7z4aIMglOYHMr67jQk7+evBVtOKvaprJFsRroFvTD+jj+TKHJG4OMkpqaDN3yM3XLNuNwKAG/KZRJ3sYXNWJNT20J9QlKOquepeKHTiY3o7FJCvjiq5Xs0TNTTJSDs=,iv:34y2Z931D6Ifqv22Fmybzm1OfHK0AJTsl6q9FBi6ga8=,tag:TyuCgq9pcNYcH581WEndeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
